// This is a shim for the app style. When the app is run in the hosted environment, the values in this file will reflect the values provided by the app user.
// Note that the values that the user provides for style are also compiled into a css file if you use the conventions provided for sass or less in the hosted environment. See the documentation for more details.
window.__settings = window.__settings || {};
window.__settings.style = {
    "layout": "two-column",
    "logo": null,
    "favicon": null,
    "header-size": "medium",
    "header-bg": "#0099E6",
    "header-divider-bar-color": "#0099E6",
    "header-brand-align": "left",
    "company-name-color": "#ffffff",
    "brand-primary": "#0099E6",
    "body-bg": "#f6f7f8",
    "main-shadows": false,
    "web_font_import": null,
    "font-family-company-name": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
    "font-family-base": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
    "font-family-footer": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
    "main-content-bg": "#ffffff",
    "main-content-color": "#686868",
    "panel-border-radius": "4px",
    "panel-border-color": "#e6e7e8",
    "link-color": "#00A8FF",
    "h-color": "#4A4A4A",
    "table-header-bg": "#f9f9f9",
    "table-header-color": "#818181",
    "footer-bg": "#f6f7f8",
    "footer-color": "#686868",
    "footer-link-color": "#00A8FF",
    "footer-size": "medium",
    "state-success-bg": "#dff0d8",
    "state-success-text": "#3c763d",
    "state-info-bg": "#d9edf7",
    "state-info-text": "#31708f",
    "state-danger-bg": "#f2dede",
    "state-danger-text": "#a94442",
    "brand-success": "#EF663B",
    "brand-info": "#5bc0de",
    "brand-danger": "#d9534f",
    "btn-primary-color": "#ffffff",
    "btn-success-color": "#ffffff",
    "btn-info-color": "#ffffff",
    "btn-warning-color": "#ffffff",
    "btn-default-bg": "#ffffff",
    "btn-default-color": "#686868",
    "product-icon-border-color": "#e6e7e8",
    "input-border-radius": "2px",
    "input-bg": "#ffffff",
    "input-color": "#555555",
    "placeholder-color": "#999999",
    "stepper-bg": "#fbfbfb",
    "stepper-color": "#00A8FF",
    "header_html": null,
    "footer_html": null,
    "logo_medium": null,
    "logo_large": null,
    "logo_square": null,
    "logo_full": null,
    "favicon_medium": null,
    "favicon_large": null,
    "favicon_square": null,
    "favicon_full": null,
}