// This is a shim for the app style. When the app is run in the hosted environment, the values in this file will reflect the values provided by the app user.
// Note that the values that the user provides for style are also compiled into a css file if you use the conventions provided for sass or less in the hosted environment. See the documentation for more details.
window.__settings = window.__settings || {};
window.__settings.style = {
    "theme": "one-column",
    "logo": null,
    "favicon": null,
    "panel-header-size": "medium",
    "panel-header-brand-align": "center",
    "company-name-color": "#ffffff",
    "panel-header-font-size": "22px",
    "brand-primary": "#3181aa",
    "body-bg": "#f6f6f6",
    "main-shadows": true,
    "web_font_import": null,
    "font-family-company-name": "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "font-family-base": "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "font-family-footer": "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "main-content-bg": "#ffffff",
    "main-content-color": "#686868",
    "link-color": "#3181aa",
    "h-color": "#686868",
    "header-bg": "#f9f9f9",
    "header-color": "#818181",
    "footer-bg": "#dfdfdf",
    "footer-color": "#5f5f5f",
    "footer-link-color": "#3181aa",
    "footer-size": "medium",
    "divider-bar-color": "#eeeeee",
    "divider-bar-width": "1px",
    "divider-bar-text-color": "#3181aa",
    "state-success-bg": "#dff0d8",
    "state-success-text": "#3c763d",
    "state-info-bg": "#d9edf7",
    "state-info-text": "#31708f",
    "state-danger-bg": "#f2dede",
    "state-danger-text": "#a94442",
    "brand-success": "#36ab0c",
    "brand-info": "#5bc0de",
    "brand-danger": "#d9534f",
    "btn-primary-color": "#ffffff",
    "btn-success-color": "#ffffff",
    "btn-info-color": "#ffffff",
    "btn-warning-color": "#ffffff",
    "btn-default-bg": "#ffffff",
    "btn-default-color": "#686868",
    "product-icon-border-color": "#ececec",
    "input-border-radius": 0,
    "input-bg": "#ffffff",
    "input-color": "#555555",
    "placeholder-color": "#999999",
    "stepper-bg": "#ffffff",
    "stepper-color": "#3181aa",
    "header_html": null,
    "footer_html": null,
    "logo_medium": null,
    "logo_large": null,
    "logo_square": null,
    "logo_full": null,
    "favicon_medium": null,
    "favicon_large": null,
    "favicon_square": null,
    "favicon_full": null
}