// Make a copy of this file and name it style.js, which can be used by the app to customize app styles.
// Note that the style values provided by the user are compiled into a css stylesheet (located in sass/style.css). This file gives you access to the raw user style input values.
// At runtime, the user's style settings will be automatically injected, providing the user's selections to the app.
window.__settings = window.__settings || {}; window.__settings.style =
    {
        "layout": "two-column",
        "body-bg": "#f6f7f8",
        "company-name-color": "#686868",
        "logo": null,
        "favicon": null,
        "header-size": "medium",
        "header-bg": "#ffffff",
        "header-brand-align": "left",
        "main-shadows": false,
        "loading-bar-bg-color": "#95dafd",
        "web_font_import": null,
        "font-family-company-name": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
        "font-family-base": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
        "font-family-footer": "-apple-system,system-ui,BlinkMacSystemFont,\"Segoe UI\",Roboto,\"Helvetica Neue\",Arial,sans-serif",
        "main-content-bg": "#ffffff",
        "main-content-shaded-bg": "#fbfbfb",
        "main-content-color": "#686868",
        "panel-border-radius": "4px",
        "panel-border-color": "#e6e7e8",
        "link-color": "#3181aa",
        "h-color": "#686868",
        "footer-bg": "#f6f7f8",
        "footer-color": "#686868",
        "footer-link-color": "#00A8FF",
        "footer-size": "medium",
        "state-success-bg": "#dff0d8",
        "state-success-text": "#3c763d",
        "state-info-bg": "#d9edf7",
        "state-info-text": "#31708f",
        "state-danger-bg": "#f2dede",
        "state-danger-text": "#a94442",
        "brand-primary": "#0099E6",
        "brand-success": "#36ab0c",
        "brand-info": "#5bc0de",
        "brand-danger": "#d9534f",
        "btn-primary-color": "#ffffff",
        "btn-success-color": "#ffffff",
        "btn-info-color": "#ffffff",
        "btn-warning-color": "#ffffff",
        "btn-default-bg": "#ffffff",
        "btn-default-color": "#686868",
        "product-icon-border-color": "#e6e7e8",
        "input-border-radius": 0,
        "input-bg": "#ffffff",
        "input-color": "#555555",
        "placeholder-color": "#999999",
        "stepper-bg": "#fbfbfb",
        "stepper-color": "#00A8FF",
        "header_html": null,
        "footer_html": null,
        "logo_medium": null,
        "logo_large": null,
        "logo_square": null,
        "logo_full": null,
        "favicon_medium": null,
        "favicon_large": null,
        "favicon_square": null,
        "favicon_full": null
    };